version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: 11.0.0 # Specify the Xcode version to use
     
    environment: 
      FL_OUTPUT_DIR: output
      
    steps:
      - checkout
      - run: pod install # Install CocoaPods dependencies
      - run: fastlane scan # Run tests using Fastlane
      - run: 
          name: Build and run tests
          environment: 
              SCAN_DEVICE: iPhone 8
              SCAN_SCHEME: AlbumApp

      # Collect XML test results data to show in the UI, and save the same XML
      # files under test-results folder in the Artifacts tab
      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output
          
workflows: 
  version: 2
  build-and-test:
      jobs:
        - build-and-test
