version: 2.1
jobs:
  build:
    macos:
      xcode: 11.5.0
    
  build-and-test:
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: tests

    steps:
      - checkout
      - run: bundle install
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  build-test:
    jobs:
      - build-and-test
